#!/bin/bash
#
# Description: init the hexo blog
# Author: Hongbo Liu
# Email: hbliu@freewheel.com
# CreatTime: 2017-03-12 15:11:25 CST

cd "$(dirname "$0")"
CURDIR="$(pwd)"
THEME_DIR="$CURDIR/themes/maupassant-hexo"

theme_init() {
	cd $THEME_DIR
	git remote add upstream https://github.com/tufu9441/maupassant-hexo.git
	git fetch --all
	git branch --set-upstream-to=upstream/master
	git checkout master
}

theme_push() {
	cd $THEME_DIR
	push
}

init() {
	npm install -g hexo-cli
	npm install
	theme_init
}

push() {
	git add .
	git commit -m 'Regular save'
	git push origin
}

source_push() {
	cd "$CURDIR"
	push
}

all_push() {
	source_push
	theme_push
}

usage() {
cat << EOF
Usage:
blog -h # blog command help
blog    # init hexo blog
blog -p # save blog source
EOF
}

main() {
	if [[ $# -eq 0 ]]; then
		init
		exit 0
	fi

	local OPT OPTARG OPTIND
	while getopts 'ph' OPT; do
		case $OPT in
			h) usage ;;
			p) all_push ;;
			?) ;;
		esac
	done
	shift $(($OPTIND - 1))
}

main $*
